CREATE USER 'demoapp'@'%' IDENTIFIED WITH mysql_native_password BY '12345678';
GRANT USAGE ON *.* TO 'demoapp'@'%';
ALTER USER 'demoapp'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `demoapp`;
GRANT ALL PRIVILEGES ON `demoapp`.* TO 'demoapp'@'%';

