-- MySQL Script generated by MySQL Workbench
-- Mon Apr  4 17:09:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema demoapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demoapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demoapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `demoapp` ;

-- -----------------------------------------------------
-- Table `demoapp`.`userdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoapp`.`userdata` (
                                                    `iduserdata` INT NOT NULL AUTO_INCREMENT,
                                                    `username` VARCHAR(255) NULL DEFAULT NULL,
    `password` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`iduserdata`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demoapp`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoapp`.`items` (
                                                 `iditems` INT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(255) NULL,
    `imgurl` VARCHAR(255) NULL,
    `price` DECIMAL(10,2) NULL,
    PRIMARY KEY (`iditems`))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
