USE demoapp;

INSERT INTO userdata (username, is_admin, pw_md5, pw_sha1, pw_bcrypt) VALUES ("max", false, "81dc9bdb52d04dc20036dbd8313ed055", "7110eda4d09e062aa5e4a390b0a572ac0d2c0220", "$2a$12$PmIOv7q6rGz5ixF0tr/OeO8BhFuluZZlZ7YPg0VDbYg9w57tpQAsm"); -- 1234
INSERT INTO userdata (username, is_admin, pw_md5, pw_sha1, pw_bcrypt) VALUES ("Robot1337", false, "7e24ceb5eac7e0712087ba5d05ba8183", "613ba53f64ace01eefbf88eec726eb3c077cc659", "$2a$12$yq8mgY6g2oE3GOIYb8tSReR3.4FdDDMURmUrrFDlRLjnAITKuB/gW"); -- ilovelinux
INSERT INTO userdata (username, is_admin, pw_md5, pw_sha1, pw_bcrypt) VALUES ("admin", true, "bd0f00d0f0365ac84c89c0e6ae19124c", "284a203d74657ab4f145c71576ed9718d4510485", "$2a$12$idWC3O/GSmPj0O0Y3qH4MubbA/5gT6ayADfxpCX93VJYRCw8d1iBK"); -- CkJQn6qScZwN2tJG

INSERT INTO items (name, price, imgurl) VALUES ("Blueberry Muffin", 13.37 ,"/uploads/blueberry-muffins-ga590dab35_1920.jpg"); -- Source: https://pixabay.com/de/photos/blaubeer-muffins-muffins-cupcakes-2136749/
INSERT INTO items (name, price, imgurl) VALUES ("Chocolate Donut" , 4.20  ,"/uploads/donut-g3fbb7b784_1920.jpg"); -- Source: https://pixabay.com/de/photos/donut-schokodonut-geb%c3%a4ckkringel-2961504/

INSERT INTO comments (item_id, title, body) VALUES (1, "Test", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
INSERT INTO comments (item_id, title, body) VALUES (1, "Test2", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
INSERT INTO comments (item_id, title, body) VALUES (2, "Test3", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
INSERT INTO comments (item_id, title, body) VALUES (2, "Test4", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
INSERT INTO comments (item_id, title, body) VALUES (2, "Test5", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");